global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'cinemapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'api:3000' ]
    scrape_interval: 60s
